### PR TITLE
fix: exports in ts

### PR DESCRIPTION
**Pull request by vasco-santos**
This fixes the exports in typescript, where the declaration files generated could not be found.

Per all the discussion in https://github.com/microsoft/TypeScript/issues/33079 , we will need to add this hacky solution to expose the declaration files in the typesversions, until typescript do support the package.json exports

Needs:

- [ ] `dist` to be removed, once this is tested in nft.storage

### CODE REVIEW

**Comment by vasco-santos** [comment]
@olizilla let me know if this fixed the issue

**Comment by olizilla** [comment]
✅ tested! This branch works for me in nft.storage api tests!

**Comment by vasco-santos** [comment]
I will create an issue as follow up to track https://github.com/microsoft/TypeScript/issues/33079 and update this once better supported

**Comment by vasco-santos** [comment]
Shipped in `0.2.2` 🚢

**Pull request merged**
